default:

  logger:
    template: "{home}/.local/share/r-devel/project.log"
    tee : FALSE

  metayer_options:
    cli.default_handler: logged_cli_handler
    metayer.cli_null: "<NULL>"
    metayer.hash_label_length: 4
