default: &default

  logger: &default_logger
    format: "{pid}|{ns}|{level}|{format(time, \"%Y-%m-%d %H:%M:%S\")}|{msg}"
    logfile: "{home}/.local/share/r-devel/project.log"
    appenders: 
      - !optenv logger::appender_console
    threshold: !optenv logger::DEBUG

  rmall_exclusions:
    - workflow

  options: &default_options
    # "pipe" cli calls into logger
    # cli.default_handler: !optenv logged_cli_handler
    cli.default_handler: !optenv cli_nullity_handler
    mty.cli_null: "<null>"

    knitr.chunk.metayer_hook: true
    mty.hash_label_length: 4

    # with_grdev defaults
    mty.fig.width: 7
    mty.fig.height: 7
    mty.fig.res: 96
    mty.fig.units: "in"

  # inches per pixel:  could be useful for setting x11 dimensions in pixel units
  display:
    ippx: 0.008477267
    ippy: 0.008550689

  rdoc_config:
    all_doc: &pandoc_shared
      pandoc_args: 
        - !with_env "--resource-path={R_HERE_HERE}/vignettes"

    output:
      html_document:
        <<: *pandoc_shared
        theme: flatly
        highlight: tango
      pdf_document:
        <<: *pandoc_shared

testing:
  <<: *default

  logger: 
    <<: *default_logger
    format: "{ns} {level} {msg}"
    logfile: "{home}/.local/share/r-devel/testing.log"
    threshold: !optenv logger::INFO

  options: &testing_options
    <<: *default_options
    cli.ansi: FALSE
    cli.unicode: FALSE
    cli.num_colors: 1
    cli.condition_unicode_bullets: FALSE

    # reproducible, uuid-like values are useful for testing
    uuid.generator: !optenv test_mty_uuid
    uuid.salt: 12345


jupyter:
  <<: *default

  logger:
    <<: *default_logger
    format: "[{level}/{ns}] {msg}"
    threshold: !optenv logger::INFO
    appenders: 
      - !optenv appender_jupyter

  options:
    <<: *testing_options

  rmall_exclusions:

