default: &default

  logger: &default_logger
    format: "{pid}|{ns}|{level}|{format(time, \"%Y-%m-%d %H:%M:%S\")}|{msg}"
    logfile: "{home}/.local/share/r-devel/project.log"
    secondary_appender: !optenv logger::appender_console
    threshold: DEBUG

  options:
    # "pipe" cli calls into logger
    # cli.default_handler: !optenv logged_cli_handler
    cli.default_handler: !optenv cli_nullity_handler
    mty.cli_null: "<null>"

    knitr.chunk.metayer_hook: true
    mty.hash_label_length: 4

    # with_grdev defaults
    mty.fig.width: 7
    mty.fig.height: 7
    mty.fig.res: 96
    mty.fig.units: "in"

  # not currently used, but maybe useful for setting x11 dimensions in pixel units
  display:
    ippx: 0.008477267
    ippy: 0.008550689


testing:
  <<: *default

  logger: 
    format: "{ns} {level} {msg}"
    logfile: "{home}/.local/share/r-devel/testing.log"
    secondary_appender: !optenv logger::appender_console
    threshold: INFO

  options:
    cli.ansi: FALSE
    cli.unicode: FALSE
    cli.num_colors: 1
    cli.condition_unicode_bullets: FALSE
    cli.default_handler: !optenv cli_nullity_handler
    mty.cli_null: "<null>"

    # reproducible, uuid-like values are useful for testing
    uuid.generator: !optenv test_mty_uuid
    uuid.salt: 12345


jupyter:
  <<: *default

  logger:
    <<: *default_logger
    format: "[{pid}/{level}/{ns}] {msg}"
    threshold: DEBUG
    secondary_appender: !optenv appender_jupyter
