default: &default

  logger: &default_logger
    format: "{pid}|{ns}|{level}|{format(time, \"%Y-%m-%d %H:%M:%S\")}|{msg}"
    logfile: !with_env "{HOME}/.local/share/r-devel/project.log"
    threshold: !optenv logger::INFO

  options: &default_options
    cli.default_handler: !optenv cli_nullity_handler
    mty.cli_null: "<null>"

    # with_grdev defaults
    mty.fig.width: 7
    mty.fig.height: 7
    mty.fig.res: 96
    mty.fig.units: "in"

  # inches per pixel:  could be useful for setting x11 dimensions in pixel units
  display:
    ippx: 0.008477267
    ippy: 0.008550689

  knitr:
    shim: |
      ```{r setup, include = FALSE}
        library(magrittr)
        library(rlang)
        library(metayer)
      ```

      ```{r, include = FALSE}
        Sys.setenv(R_CONFIG_ACTIVE = "jupyter")

        # knitr options [ref](https://yihui.org/knitr/options/) documentation; 
        knitr::opts_chunk$set(
          metayer_hook = TRUE,
          comment = "",
          fig.path = "assets/knitr/",
          
          # c.f., _pkgdown \ templates \ includes
          class.output = c("sourceCode", "rOutput")
        )

        knitr::opts_knit$set(
          root.dir = here::here("vignettes")
        )

        knitr::knit_hooks$set(
          metayer_hook = knitr_metayer_hook
        )
      ```


  pander:
    evalsOptions:
      graph.dir: "assets/pander"

  # rmarkdown configuration; jupyter YAML header
  rdoc_config:
    all_doc: &pandoc_shared
      pandoc_args: 
        - !with_env "--resource-path={R_HERE_HERE}/vignettes"

    output:
      html_vignette:
        toc: true
        toc_depth: 2
      html_document:
        <<: *pandoc_shared
        theme: flatly
        highlight: tango
      pdf_document:
        <<: *pandoc_shared

    vignette: |
      %\VignetteIndexEntry{ {{article_name}} }
      %\VignetteEngine{knitr::rmarkdown}
      %\VignetteEncoding{UTF-8}


  # rm.all exclusions
  rmall_exclusions:
    - workflow


testing:
  <<: *default

  logger: 
    <<: *default_logger
    format: "{ns} {level} {msg}"
    logfile: !with_env "{HOME}/.local/share/r-devel/testing.log"
    threshold: !optenv logger::INFO
    appenders: 
      - !optenv logger::appender_console

  options: &testing_options
    <<: *default_options
    cli.ansi: FALSE
    cli.unicode: FALSE
    cli.num_colors: 1
    cli.condition_unicode_bullets: FALSE

    # reproducible, uuid-like values from mty_uuid
    uuid.generator: !optenv test_mty_uuid
    uuid.generator.seed: 12345


jupyter:
  <<: *default

  logger:
    <<: *default_logger
    format: "[{level}/{ns}] {msg}"
    threshold: !optenv logger::INFO
    appenders: 
      - !optenv appender_jupyter

  options:
    <<: *testing_options
    knitr.chunk.error: FALSE

  rmall_exclusions:

